### ISSUE TITLE
Cannot GET /p/testtest/subscribe=Pov7AX3B7LJvcaXRB3syqiVB7

### ISSUE THREAD

**Issue by cbarillet** [JohnMcLear/ep_email_notifications#24]
Hi,
When I click on the link in the email (http://pad.cyril-barillet.com/p/testtest/subscribe=Pov7AX3B7LJvcaXRB3syqiVB7), I have this message: Cannot GET /p/testtest/subscribe=Pov7AX3B7LJvcaXRB3syqiVB7
Best regards.

**Comment by JohnMcLear** [comment]
Were you able to fix this?  Can this be closed due to the latest merge?
