### ISSUE TITLE
Link of confirmation email doesn't work

### ISSUE THREAD

**Issue by froiloc** [JohnMcLear/ep_email_notifications#27]
Hi,

I have installed ep_email_notification without any problems.
I managed to send an email containing the link
https://domain.com/p/padname/subscribe=confirmationcode

The issue I have is the response I get:

Its an error 404 with the message:
Cannot GET /p/padname/subscribe=confirmationcode

The OS is Linux Ubuntu Server 12.04 LTS

What am I doing wrong? Why doesn't the hook fire? Which hook should fire? How can I test this best?
Thank you for your help with this issue.

Cheers,
froiloc

**Comment by JohnMcLear** [comment]
https://github.com/JohnMcLear/ep_email_notifications/blob/master/index.js#L11
Add a ``console.warn("hello")`` line after this..  See if it hits it..

If it does add similar line after this: https://github.com/JohnMcLear/ep_email_notifications/blob/master/index.js#L49

My guess is the route defined at https://github.com/JohnMcLear/ep_email_notifications/blob/master/index.js#L11 is to blame!

**Comment by froiloc** [comment]
Hello John,

thanks for your quick reply. The Warning doesn't hit. My guess is that the hook doesn't fire. What would be the best approach to check if this is the case?

It feels like this index.js isn't loaded at all. Should it be loaded by the browser when working with the pad? I cannot see it in the list of loaded files.

Maybe another plugin causes the problem here and prevents that ep_email_notification is executed correctly.

These are the plugins I have installed:

adminpads
colors
copy_paste_images
copy_paste_select_all
delete_empty_pads
draw
email_notifications
embedmedia
headings
horizontal_line
list_pads
mammoth
mediawiki
padlist
printer
scrollto
scrolltoanchor
search
spellcheck
tables2
themes

I hope to narrow the problem down. Thank you very much for your kind support. :)

Cheers,
froiloc

**Comment by JohnMcLear** [comment]
Look on server log not client

On 24 Jun 2015 14:48, froiloc <notifications@github.com> wrote:

Hello John,

thanks for your quick reply. The Warning doesn't hit. My guess is that the hook doesn't fire. What would be the best approach to check if this is the case?

It feels like this index.js isn't loaded at all. Should it be loaded by the browser when working with the pad? I cannot see it in the list of loaded files.

Maybe another plugin causes the problem here and prevents that ep_email_notification is executed correctly.

These are the plugins I have installed:

adminpads
colors
copy_paste_images
copy_paste_select_all
delete_empty_pads
draw
email_notifications
embedmedia
headings
horizontal_line
list_pads
mammoth
mediawiki
padlist
printer
scrollto
scrolltoanchor
search
spellcheck
tables2
themes

I hope to narrow the problem down. Thank you very much for your kind support. :)

Cheers,
froiloc

**Comment by froiloc** [comment]
Hi John,

thanks staying put in this issue. :) 
I couldn't find the message in the server's log. So I added the console.warn Message in line 10. So right before the regular expression.

I found that message form line 10 in the log right after the server starts. It is the next line in the log after the SSL INFO about the Certificate Authority.

But it doesn't show up when I open any page of the pad nor when I open the link sent in the email.

When is the hook supposed to be fired? My guess was that it is called whenever a page is loaded. But this is not the case.

How should I proceed?

**Comment by froiloc** [comment]
I assume it has nothing to do with the current issue, but I failed to pass 3 frontend tests for chat_load_messages.js : "checks initial message count", "loads more messages" and "checks for button vanishing". Also I cannot run the backend test successfully. It tells me with each test
     Error: connect ECONNREFUSED
      at exports._errnoException (util.js:746:11)
      at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1010:19)

Maybe this gives you a clue about what could be wrong.

**Comment by JohnMcLear** [comment]
@froiloc disable plugins until you find out which one is breaking that.

**Comment by JohnMcLear** [comment]
I just tested this plugin and both http://10.0.0.12:9001/p/egZcu4YJNq/subscribe=hello and http://10.0.0.12:9001/p/egZcu4YJNq/unsubscribe=hello return the correct values.

**Comment by froiloc** [comment]
all right. I will disable all the plugins one by one. Maybe I need a clean reinstall in the end. I will see. I come back to you. Maybe I will find a clue. Thanks.

**Comment by froiloc** [comment]
I switched to DEBUG mode at the server after I removed all plugins. No success so far. The other plugins that were installed most likely didn't cause the issue.

I get the following Log messages:

[2015-06-24 17:34:55.077] [DEBUG] SessionStore - GET 2LOBj6N8pvlTv8GLvVSqyo5BXzBeAYLI
[2015-06-24 17:34:55.080] [DEBUG] ueberDB - GET    - sessionstorage:2LOBj6N8pvlTv8GLvVSqyo5BXzBeAYLI - {"cookie":{"path":"/","_expires":null,"originalMaxAge":null,"httpOnly":true}} - from database 
[2015-06-24 17:34:55.085] [DEBUG] SessionStore - SET 2LOBj6N8pvlTv8GLvVSqyo5BXzBeAYLI
[2015-06-24 17:34:55.086] [DEBUG] ueberDB - SET    - sessionstorage:2LOBj6N8pvlTv8GLvVSqyo5BXzBeAYLI - {"cookie":{"path":"/","_expires":null,"originalMaxAge":null,"httpOnly":true}} - to buffer
[2015-06-24 17:34:55.088] [DEBUG] http - 404, GET /p/padname/subscribe=iYIdjfQ27PGWblwk5cp7pvPys
[2015-06-24 17:34:55.116] [INFO] ueberDB - Flushed 1 values

I will try to reinstall etherpad-lite from scratch. My installation seems to be messed up somehow.
I'll be back when I come closer to a solution.

**Comment by froiloc** [comment]
I reinstalled etherpad-lite now using git clone.
Then I called npm i ep_email_notifications.
It installed everything without a warning, error or anything.

I just added the settings for ep_email_notifications in settings.json

  "ep_email_notifications" : {
    "panelDisplayLocation": { // Where you want to have the subscription panel
      "mysettings": true,
      "popup": true
    },
    "checkFrequency" : 6000, // checkFrequency = How frequently(milliseconds) to check for pad updates -- Move me to the settings file
    "staleTime": 30000,  // staleTime = How stale(milliseconds) does a pad need to be before notifying subscribers?  Move me to settings
    "fromName" : "mydomain-Etherpad",
    "fromEmail" : "pad@mydomain.com",
    "urlToPads" : "https://mydomain.com/p/", // urlToPads = The URL to your pads note the trailing /
    "emailServer" : { // See https://github.com/eleith/emailjs for settings
//      "host" : "127.0.0.1"
      "host" : "smtp.mydomain.com",
      "port" : 587,
      "domain" : "mydomain.com",
      "username" : "myusername",
      "password" : "mypassword",
      "tls" : true,
      "authentication" : ["email.authentication.XOAUTH2"] //email.authentication.PLAIN
    }
  },

Then I started the server with
bin/run.sh

Nevertheless it shows the same behavior.

The response in the browser (client) is "HTTP ERROR 404" and the message 
"Cannot GET /p/padname/subscribe=Zci84jTCiCXDHjKARreC5Zm3O"

I'm stuck.

**Comment by JohnMcLear** [comment]
Try use the default settings, see if you are still stuck...

**Comment by JohnMcLear** [comment]
Are you reverse proxy rewriting or something?

**Comment by froiloc** [comment]
I do use a reverse proxy but not while I am testing. I will set to the defaults.

"ep_email_notifications" : {
    "panelDisplayLocation": { // Where you want to have the subscription panel
      "mysettings": true,
      "popup": true
    },
    "checkFrequency": "6000", // checkFrequency = How frequently(milliseconds) to check for pad updates -- Move me to the settings file
    "staleTime": "30000",  // staleTime = How stale(milliseconds) does a pad need to be before notifying subscribers?  Move me to settings
    "fromName": "Etherpad SETTINGS FILE!",
    "fromEmail": "pad@etherpad.org",
    "urlToPads": "https://172.16.0.22:9001/p/", // urlToPads = The URL to your pads note the trailing /
    "emailServer": { // See https://github.com/eleith/emailjs for settings
      "host": "127.0.0.1"
    }
  },

Same behavior.

**Comment by JohnMcLear** [comment]
When you clone are you cloning develop or master?  Try develop branch..

Also try installing ep_email_notifications using git clone..  It might be that I haven't pushed any fixes to npm yet...

**Comment by froiloc** [comment]
Hi John,

I made everything new from scratch.
I used git to clone the master of etherpad-lite.
Then I installed ep_email_notifications using git clone.
Then I created the directory "node_modules" in node_modules/ep_email_notifications, where I did:
git clone https://github.com/chriso/validator.js validator
git clone https://github.com/eleith/emailjs emailjs
git clone https://github.com/bnoordhuis/node-buffertools buffertools

Then I changed to validator directory and used "make" to install it properly.
Then I changed to emailjs directory and copied the "node_modules" directory of an old installation here, since I could find the make file.

Then all dependencies were met.

I started the etherpad-lite server again and tested the link. ..... AND IT WORKED.

So I guess the npm isn't correct.

Thank you very much for your kind support. I'll report back if I face any other trouble.

**Comment by JohnMcLear** [comment]
I will publish a new version today, apologies..

**Comment by JohnMcLear** [comment]
New version published :) Tnx

**Comment by froiloc** [comment]
No need to apologize. You are awesome. Once again. Thank you very much for taking your time to help me. :)
